import type { GameItemDefinition } from '@/game/items/types';

export const BASE_ITEM_DATABASE: GameItemDefinition[] = [
  {
    id: 'old-rod',
    name: 'Old Rod',
    category: 'tool',
    description: 'A worn fishing rod. Use near water to try and fish.',
    imageUrl: '',
    misuseText: 'Press F while near water to fish!',
    effectType: 'tool_action',
    effectConfig: {
      actionId: 'fishing',
      power: 0.2,
      requiresFacingTileKeyword: ['water'],
      successText: 'You cast your line into the water.',
    },
    value: 0.2,
    consumable: false,
    maxStack: 1,
    isActive: true,
    starterGrantAmount: 0,
  },
  {
    id: 'field-bandage',
    name: 'Field Bandage',
    category: 'healing',
    description: 'Heals one squad critter by 20 HP.',
    imageUrl: '',
    misuseText: 'Choose an injured squad critter to use this.',
    successText: '<Critter> was healed by X HP!',
    effectType: 'heal_flat',
    effectConfig: {
      healAmount: 20,
      curesStatus: false,
    },
    value: 20,
    consumable: true,
    maxStack: 99,
    isActive: true,
    starterGrantAmount: 3,
  },
  {
    id: 'trainer-charm',
    name: 'Trainer Charm',
    category: 'equipment',
    description: 'A trinket that will eventually be equip-able to critters.',
    imageUrl: '',
    misuseText: 'Equipment support is coming soon.',
    effectType: 'equip_stub',
    effectConfig: {
      slot: 'trinket',
    },
    consumable: false,
    maxStack: 1,
    isActive: true,
    starterGrantAmount: 0,
  },
];
